version: "1"
name: "neighbourhood"
services:
  db:
    container_name: neighbourhood-postgres
    image: postgres:latest
    volumes:
      - ./data:/docker-entrypoint-initdb.d:ro
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
  api:
    container_name: neighbourhood-api
    image: node:slim
    volumes:
      - type: bind
        source: ./api
        target: /neighbourhood
    working_dir: /neighbourhood
    ports: 
      - 3000:3000
    environment:
      - PORT=3000
      - PGHOST=db
      - PGUSER=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=password
      - PGPORT=5432
    command: bash -c "npm install && npm run seedDev && npm run dev"
volumes:
  dbdata:
